services:
  api_server:
    container_name: api-server
    build:
      context: .
      dockerfile: Pilot.Api/Dockerfile
    ports:
      - 8010:8080
    depends_on:
      receiver_server:
        condition: service_started

  identity_server:
    build:
      context: .
      dockerfile: Pilot.Identity/Dockerfile
    ports:
      - 8020:8080
    depends_on:
      pilot_identity_mysql:
        condition: service_healthy
        
  receiver_server:
    build:
      context: .
      dockerfile: Pilot.Receiver/Dockerfile
    ports:
      - 8030:8080
    depends_on:
      pilot_mysql:
        condition: service_healthy

  messenger_server:
    build:
      context: .
      dockerfile: Pilot.Messenger/Dockerfile
    ports:
      - 8040:8080
    depends_on:
      pilot_messenger_mysql:
        condition: service_healthy

  storage_server:
    build:
      context: .
      dockerfile: Pilot.Storage/Dockerfile
    ports:
      - 8040:8080
    depends_on:
      pilot_messenger_mysql:
        condition: service_healthy

  rabbitmq:
    container_name: pilot-rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    container_name: pilot-redis
    image: redis
    ports:
      - 6379:6379

  pilot_identity_mysql:
    container_name: pilot-identity-mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: PilotIdentityDb
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      
  pilot_mysql:
    container_name: pilot-mysql
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: PilotDb
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      
  pilot_messenger_mysql:
    container_name: pilot-messenger-mysql
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: PilotMessengerDb
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      
  pilot_storage_mysql:
    container_name: pilot-storage-mysql
    image: mysql:8.0
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: PilotStorageDb
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10