name: Combined Workflow

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  gateway:
    name: Gateway
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Restore Messenger project
        run: dotnet restore ./Pilot.Messenger/Pilot.Messenger.csproj

      - name: Build Messenger project
        run: dotnet build ./Pilot.Messenger/Pilot.Messenger.csproj --configuration Release --no-restore

      - name: Restore Identity project
        run: dotnet restore ./Pilot.Identity/Pilot.Identity.csproj

      - name: Build Identity project
        run: dotnet build ./Pilot.Identity/Pilot.Identity.csproj --configuration Release --no-restore

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Test.Api/Test.Api.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Test.Api/Test.Api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Test.Api/Test.Api.csproj --configuration Release --no-build

  receiver:
    name: Receiver
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Restore Messenger project
        run: dotnet restore ./Pilot.Messenger/Pilot.Messenger.csproj

      - name: Build Messenger project
        run: dotnet build ./Pilot.Messenger/Pilot.Messenger.csproj --configuration Release --no-restore

      - name: Restore Identity project
        run: dotnet restore ./Pilot.Identity/Pilot.Identity.csproj

      - name: Build Identity project
        run: dotnet build ./Pilot.Identity/Pilot.Identity.csproj --configuration Release --no-restore

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj --configuration Release --no-build

  identity:
    name: Identity
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Restore Messenger project
        run: dotnet restore ./Pilot.Messenger/Pilot.Messenger.csproj

      - name: Build Messenger project
        run: dotnet build ./Pilot.Messenger/Pilot.Messenger.csproj --configuration Release --no-restore

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Test.Identity/Test.Identity.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Test.Identity/Test.Identity.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Test.Identity/Test.Identity.csproj --configuration Release --no-build

  messenger:
    name: Messenger
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Restore Identity project
        run: dotnet restore ./Pilot.Identity/Pilot.Identity.csproj

      - name: Build Identity project
        run: dotnet build ./Pilot.Identity/Pilot.Identity.csproj --configuration Release --no-restore

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Test.Messenger/Test.Messenger.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Test.Messenger/Test.Messenger.csproj --configuration Release --no-build