name: Checkout

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: TestForest Dashboard
        uses: test-summary/action@v2.4
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore Contract project
        run: dotnet restore ./Pilot.Contracts/Pilot.Contracts.csproj

      - name: Build Contract project
        run: dotnet build ./Pilot.Contracts/Pilot.Contracts.csproj --configuration Release --no-restore

#      - name: List directory contents
#        run: ls -R

      - name: Restore Messenger project
        run: dotnet restore ./Pilot.Messenger/Pilot.Messenger.csproj --source https://api.nuget.org/v3/index.json --source ../Pilot.Contracts/bin/Release/

      - name: Build Messenger project
        run: dotnet build ./Pilot.Messenger/Pilot.Messenger.csproj --configuration Release --no-restore

      - name: Restore Identity project
        run: dotnet restore ./Pilot.Identity/Pilot.Identity.csproj --source https://api.nuget.org/v3/index.json --source ../Pilot.Contracts/bin/Release/

      - name: Build Identity project
        run: dotnet build ./Pilot.Identity/Pilot.Identity.csproj --configuration Release --no-restore
      
      - name: Restore API project
        run: dotnet restore ./Pilot.Api/Pilot.Api.csproj --source https://api.nuget.org/v3/index.json --source ../Pilot.Contracts/bin/Release/

      - name: Build API project
        run: dotnet build ./Pilot.Api/Pilot.Api.csproj --configuration Release --no-restore 

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Pilot.Tests.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Pilot.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Pilot.Tests.csproj --configuration Release --no-build
        
      - name: Publish
        run: dotnet publish ./Pilot.Api/Pilot.Api.csproj --configuration Release --no-build
        
