name: Checkout

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "**" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      



#      - name: Restore Contract project
#        run: dotnet restore ./Pilot.Contracts/Pilot.Contracts.csproj
#
#      - name: Build Contract project
#        run: dotnet build ./Pilot.Contracts/Pilot.Contracts.csproj --configuration Release --no-restore

      - name: Restore API project
        run: dotnet restore ./Pilot.Api/Pilot.Api.csproj --source https://api.nuget.org/v3/index.json 

      - name: Build API project
        run: dotnet build ./Pilot.Api/Pilot.Api.csproj --configuration Release --no-restore 

      - name: Restore Contract project
        run: dotnet restore ./Pilot.Tests/Pilot.Tests.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Pilot.Tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Pilot.Tests.csproj --configuration Release --no-build
        
      - name: Publish
        run: dotnet publish ./Pilot.Api/Pilot.Api.csproj --configuration Release --no-build
        
