name: Receiver

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Restore Contract project
        run: dotnet restore ./Pilot.Contracts/Pilot.Contracts.csproj

      - name: Build Contract project
        run: dotnet build ./Pilot.Contracts/Pilot.Contracts.csproj --configuration Release --no-restore

      - name: Restore Messenger project
        run: dotnet restore ./Pilot.Messenger/Pilot.Messenger.csproj --source https://api.nuget.org/v3/index.json --source ../Pilot.Contracts/bin/Release/

      - name: Build Messenger project
        run: dotnet build ./Pilot.Messenger/Pilot.Messenger.csproj --configuration Release --no-restore

      - name: Restore Identity project
        run: dotnet restore ./Pilot.Identity/Pilot.Identity.csproj --source https://api.nuget.org/v3/index.json --source ../Pilot.Contracts/bin/Release/

      - name: Build Identity project
        run: dotnet build ./Pilot.Identity/Pilot.Identity.csproj --configuration Release --no-restore

      - name: Restore Base test project
        run: dotnet restore ./Pilot.Tests/Test.Base/Test.Base.csproj

      - name: Build Base test  project
        run: dotnet build ./Pilot.Tests/Test.Base/Test.Base.csproj --configuration Release --no-restore

      - name: Restore Tests project
        run: dotnet restore ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj

      - name: Build Tests
        run: dotnet build ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Pilot.Tests/Test.Receiver/Test.Receiver.csproj --configuration Release --no-build